Kafka:
  addr: localhost:9092
  msg_chan: 10000

etcd:
  addr: localhost:2379
  collect_key: log_collect

HaloLog:
  topic: halo_log
  path: /TestLog/Halo/halo.log

SqlLog:
  topic: sql_log
  path: /TestLog/Sql/sql.log

